site_name: Written on the Wall III
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
nav:
  - Home: index.md
  - Conjectures:
      - 001: conjectures/001-independence-vs-residue.md
